# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Brewtagger < Formula
  desc "Tag casks with a color in /applications so we know they are homebrew managed"
  homepage "https://github.com/dewey/brewtagger"
  url "https://github.com/dewey/brewtagger/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "8aa81f57470889d26033bdab493169af1b2c2cadf08d4aa11cd120a42330df4f"

  depends_on "go" => :build
  depends_on "tag"

  def install
    system "go", "build", "-o", "brewtagger"
    bin.install "brewtagger"
    prefix.install "com.github.dewey.brewtagger.plist"
  end

  test do
    assert_match("brewtagger version", shell_output("brewtagger --version"))
  end
end
