name: Release

on:
  release:
    types: [published]

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to Homebrew
        uses: Justintime50/homebrew-releaser@v2
        with:
          homebrew_owner: dewey
          homebrew_tap: brewtagger
          formula_folder: Formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: github-actions
          commit_email: github-actions@github.com
          install: |
            system "go", "build", "-o", "brewtagger"
            bin.install "brewtagger"
            prefix.install "com.github.dewey.brewtagger.plist"
          test: 'assert_match("brewtagger version", shell_output("brewtagger --version"))'
          depends_on: |
            "go" => :build
            "tag"
          debug: false
          skip_commit: false 